### ISSUE TITLE
Text shadow?

### ISSUE THREAD

**Issue by Humeira** [mscraftsman/devcon2015#1]
I think that the text-shadow is a bit uncalled-for.

**Comment by jochenkirstaetter** [comment]
I assume, that you refer to writing across the top banner, right?

Could be, at least it's more readable than without.
Please suggest alternatives and other visual improvements for better experience than what we have at the moment.

**Comment by Humeira** [comment]
Yes, the banner.
I think a better typography and colour together will be ok.

**Comment by jochenkirstaetter** [comment]
Hmmm, alright. 
Just bear in mind that the colour palette has to be consistent all over the site.

**Comment by jochenkirstaetter** [comment]
Nirvan provided an improved version.
