### ISSUE TITLE
Scroll improvements

### ISSUE THREAD

**Issue by Nayar** [mscraftsman/devcon2015#2]
Clicking on Sessions or Extras from top menu yields this:

![capture](https://cloud.githubusercontent.com/assets/454815/6017877/be6204f2-abab-11e4-9232-b9ba0619a386.JPG)
![capture1](https://cloud.githubusercontent.com/assets/454815/6017878/be77fa0a-abab-11e4-9b3c-a2b280edd050.JPG)

Maybe a margin-top with the body might fix it as the nav menu is not taking any "place" right now causing the headers to not be readable. Or maybe the scroller could be configured to go more down

**Comment by jochenkirstaetter** [comment]
Try your luck to fix it... 

I'm focusing on the remaining and missing content for now.

**Comment by jochenkirstaetter** [comment]
Fixed.
That's a behaviour in an older version of ui-router which was on by default. I adjusted the setting because latest version of ui-router generates HTTP 406 errors.
